CREATE TABLE `agents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`whatsapp` varchar(50),
	`specialties` text,
	`languages` text,
	`status` enum('active','inactive','on_leave') NOT NULL DEFAULT 'active',
	`rating` int DEFAULT 5,
	`totalBookings` int DEFAULT 0,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `agents_id` PRIMARY KEY(`id`),
	CONSTRAINT `agents_email_unique` UNIQUE(`email`)
);
--> statement-breakpoint
CREATE TABLE `bookings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contactName` varchar(255) NOT NULL,
	`contactEmail` varchar(320) NOT NULL,
	`contactPhone` varchar(50) NOT NULL,
	`contactWhatsApp` varchar(50),
	`arrivalDate` timestamp NOT NULL,
	`departureDate` timestamp NOT NULL,
	`numberOfAdults` int NOT NULL DEFAULT 1,
	`hasChildren` int NOT NULL DEFAULT 0,
	`numberOfChildren` int,
	`childrenAges` text,
	`includesHotels` int NOT NULL DEFAULT 0,
	`hotelPreferences` text,
	`includesGuide` int NOT NULL DEFAULT 0,
	`includesTrip` int NOT NULL DEFAULT 0,
	`includesAttractions` int NOT NULL DEFAULT 0,
	`selectedAttractions` text,
	`includesFood` int NOT NULL DEFAULT 0,
	`foodPreferences` text,
	`needsShabbatHotel` int NOT NULL DEFAULT 0,
	`shabbatHotel` varchar(255),
	`pickupPoint` varchar(255) NOT NULL,
	`customPickupLocation` text,
	`dropoffPoint` varchar(255) NOT NULL,
	`customDropoffLocation` text,
	`suggestedDestinations` text,
	`specialRequests` text,
	`dietaryRestrictions` text,
	`budget` varchar(100),
	`status` enum('pending','confirmed','in_progress','completed','cancelled') NOT NULL DEFAULT 'pending',
	`totalPrice` int,
	`depositPaid` int DEFAULT 0,
	`balancePaid` int DEFAULT 0,
	`assignedAgentId` int,
	`source` varchar(100) DEFAULT 'website',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `bookings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `financialRecords` (
	`id` int AUTO_INCREMENT NOT NULL,
	`bookingId` int NOT NULL,
	`type` enum('revenue','cost','refund') NOT NULL,
	`category` varchar(100) NOT NULL,
	`amount` int NOT NULL,
	`currency` varchar(10) NOT NULL DEFAULT 'THB',
	`description` text,
	`paymentMethod` varchar(50),
	`paymentDate` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `financialRecords_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50),
	`source` varchar(100) DEFAULT 'website',
	`interestedTours` text,
	`message` text,
	`status` enum('new','contacted','quoted','converted','lost') NOT NULL DEFAULT 'new',
	`convertedToBookingId` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
