CREATE TABLE `blogPosts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(500) NOT NULL,
	`titleHe` varchar(500) DEFAULT '',
	`slug` varchar(500) NOT NULL,
	`excerpt` text,
	`excerptHe` text,
	`content` text NOT NULL,
	`contentHe` text,
	`coverImage` varchar(1000),
	`category` varchar(100),
	`tags` text,
	`isPublished` int NOT NULL DEFAULT 0,
	`publishedAt` timestamp,
	`author` varchar(255) DEFAULT 'WIRO 4x4',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blogPosts_id` PRIMARY KEY(`id`),
	CONSTRAINT `blogPosts_slug_unique` UNIQUE(`slug`)
);
